# Generated by Django 5.2.12 on 2026-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('CARGOADMIN', 'Cargo Admin'), ('CLIENTADMIN', 'Client Admin'), ('STAFF', 'Staff'), ('CLIENT', 'Client')], default='CLIENT', help_text='User role in the system', max_length=20),
        ),
    ]
