# Generated by Django 5.2.12 on 2026-03-12 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='weight',
            new_name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='cargo',
            name='arrived_nairobi_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivered_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dispatch_image',
            field=models.ImageField(blank=True, null=True, upload_to='cargo/dispatches/'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dispatched_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dispatcher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dispatcher_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_image',
            field=models.ImageField(blank=True, null=True, upload_to='cargo/pickups/'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='processing_at_origin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='shipment_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('Pickup Requested', 'Pickup Requested'), ('Shipment Created', 'Shipment Created'), ('Processing at Origin', 'Processing at Origin'), ('In Transit', 'In Transit'), ('Arrived Nairobi Hub', 'Arrived Nairobi Hub'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Pickup Requested', max_length=50),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
