# Generated by Django 5.2.12 on 2026-03-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_cargo_client_rename_weight_cargo_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='dest_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dest_contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dest_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='priority',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='cargo',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('Air', 'Air Freight'), ('Sea', 'Sea Freight')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='volume_cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
