# Generated by Django 5.2.12 on 2026-03-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='clearance_charges_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='excise_duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='idf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Import Declaration Fee', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rdl',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Railway Development Levy', max_digits=12),
        ),
    ]
