# Generated by Django 5.2.12 on 2026-03-26 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_invoice_payment_method_invoice_payment_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='import_vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Import VAT paid at KRA', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='port_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Port/terminal charges', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Client this invoice belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='clearance_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Clearance fees paid to third parties', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customs_duty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Import Duty', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5),
        ),
    ]
