# Generated by Django 5.2.12 on 2026-03-26 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_invoice_import_vat_invoice_port_charges_invoice_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='clearance_submitted',
            field=models.BooleanField(default=False, help_text='Staff has submitted charges for admin review'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='clearance_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='clearance_submitted_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who submitted the charges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_clearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('clearance_submitted', 'Clearance Charges Submitted'), ('clearance_approved', 'Clearance Charges Approved'), ('clearance_rejected', 'Clearance Charges Rejected'), ('invoice_paid', 'Invoice Paid'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shipments.invoice')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
