# Generated by Django 5.2.12 on 2026-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_invoice_clearance_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='intake_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('Pickup Requested', 'Pickup Requested'), ('Shipment Created', 'Shipment Created'), ('Processing at Origin', 'Processing at Origin'), ('In Transit', 'In Transit'), ('Arrived Nairobi Hub', 'Arrived Nairobi Hub'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], db_index=True, default='Pickup Requested', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('proforma', 'Proforma Invoice'), ('final', 'Final Invoice')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10),
        ),
    ]
