# Generated by Django 5.2.12 on 2026-03-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_add_status_intake_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('retired', 'Retired'), ('expired', 'Expired')], db_index=True, default='draft', max_length=10),
        ),
    ]
