# Generated by Django 5.2.12 on 2026-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_add_retired_expired_invoice_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='compensation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='compensation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='compensation_reference',
            field=models.CharField(blank=True, help_text='Insurance claim or payment reference', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='incident_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='incident_declared_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='incident_location',
            field=models.CharField(blank=True, help_text='Where cargo was declared lost or incident occurred', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='incident_notes',
            field=models.TextField(blank=True, help_text='Details about the incident', null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='incident_status',
            field=models.CharField(blank=True, help_text='Lost, Delayed, Not Picked Up, Compensated', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('Pickup Requested', 'Pickup Requested'), ('Shipment Created', 'Shipment Created'), ('Processing at Origin', 'Processing at Origin'), ('In Transit', 'In Transit'), ('Arrived Nairobi Hub', 'Arrived Nairobi Hub'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Lost', 'Lost'), ('Delayed', 'Delayed'), ('Not Picked Up', 'Not Picked Up'), ('Compensated', 'Compensated')], db_index=True, default='Pickup Requested', max_length=50),
        ),
    ]
