# Generated by Django 5.2.12 on 2026-03-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_add_mpesa_visa_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='sticker_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='sticker_attached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='sticker_attached_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='sticker_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cargo/stickers/'),
        ),
    ]
