# Generated by Django 5.2.12 on 2026-03-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_add_sticker_attachment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='dest_address_line',
            field=models.CharField(blank=True, help_text='e.g. House 12, Riverside Drive', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dest_area',
            field=models.CharField(blank=True, help_text='e.g. Westlands', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dest_city',
            field=models.CharField(blank=True, help_text='e.g. Nairobi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dest_postal_code',
            field=models.CharField(blank=True, help_text='e.g. 00100', max_length=20, null=True),
        ),
    ]
