# Generated by Django 5.2.12 on 2026-03-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_add_dest_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='sticker_print_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the sticker has been printed'),
        ),
    ]
