# Generated by Django 5.2.12 on 2026-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_add_sticker_print_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='dispatcher_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('clearance_submitted', 'Clearance Charges Submitted'), ('clearance_approved', 'Clearance Charges Approved'), ('clearance_rejected', 'Clearance Charges Rejected'), ('invoice_paid', 'Invoice Paid'), ('credit_note_requested', 'Credit Note Requested'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
