# Generated by Django 5.2.12 on 2026-03-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0017_add_dispatcher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='dispatch_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dispatch charges for finance reporting', max_digits=12),
        ),
        migrations.CreateModel(
            name='DispatchHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='e.g. Wells Fargo, Super Metro, rider name', max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-usage_count', '-last_used'],
                'unique_together': {('service_name', 'contact_name')},
            },
        ),
    ]
