# Generated by Django 5.2.12 on 2026-03-30 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0019_invoice_reimbursable_vat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='pickup_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff assigned to pick up the cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='warehouse_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='warehouse_received_by',
            field=models.ForeignKey(blank=True, help_text='Staff who received the cargo at warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_received_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('Pickup Requested', 'Pickup Requested'), ('Pickup Assigned', 'Pickup Assigned'), ('Pickup Closed', 'Pickup Closed'), ('Received at Warehouse', 'Received at Warehouse'), ('Shipment Created', 'Shipment Created'), ('Processing at Origin', 'Processing at Origin'), ('In Transit', 'In Transit'), ('Arrived Nairobi Hub', 'Arrived Nairobi Hub'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Lost', 'Lost'), ('Delayed', 'Delayed'), ('Not Picked Up', 'Not Picked Up'), ('Compensated', 'Compensated')], db_index=True, default='Pickup Requested', max_length=50),
        ),
    ]
